### ISSUE TITLE
Passing context

### ISSUE THREAD

**Issue by kuon** [apotonick/representable#125]
How can I pass a context when I generate a hash this way?

```

# File A

class MyDecorator < Representable::Decorator
  include Representable::Hash

  property :needcontext, :getter => -> (*) { #user context here }

end

# File B
context = {:foo => :bar}
MyDecorator.represent(obj).to_hash(context # pass somehow)
```

I'd like to be able to use `context` in my decorator.

**Comment by apotonick** [comment]
I'd say ***RTFM!*** but my twitter bio says "Don't be a dick", so here we go :grinning: https://github.com/apotonick/representable#passing-options

**Comment by kuon** [comment]
I read the README 3 times and I missed this 3 times.

Sorry, and thanks.

**Comment by apotonick** [comment]
No problem, buddy. I am gonna discuss this in my book as well! https://leanpub.com/trailblazer *hint*
