### ISSUE TITLE
What is the difference between getter/setter and reader/writer ?

### ISSUE THREAD

**Issue by yesmeck** [apotonick/representable#133]

**Comment by apotonick** [comment]
Hi Wei,

`:getter`/`:setter` only override the way representable retreives/sets values on the represented object. `:reader` completely overwrites the entire process, it gives you access to the parsed document and then it's up to you what to do with it. The same applies for the other way with `:writer` where you have to write to the actual document, etc.

The Trailblazer book will cover this soon, I recommend to buy it now before it's sold out. :stuck_out_tongue_winking_eye:

**Comment by yesmeck** [comment]
Thanks @apotonick , have bought your book on Leanpub.

**Comment by apotonick** [comment]
:heart:
