### ISSUE TITLE
feature: 'required' properties

### ISSUE THREAD

**Issue by grepory** [apotonick/representable#134]
I'm looking at using Representable for modeling configuration files with required fields and coercion for validation. Is it acceptable to add a boolean required option to decorators that causes render/parse failure if the field is missing?

I'm currently working on implementing this just for my project, but thought it may be useful to others and makes a little sense to live inside the library? Or an extension to the core library? Thoughts/suggestions?

<3 representable thanks so much.

**Comment by apotonick** [comment]
Hm, validations should not go into Representable. This is handled with `Contract` objects from Reform. This will never be mixed together, as Representable does the serialisation/deserialisation and Reform does validation. This is what most other similar gems do wrong, in my opinion.

Have you had a look at contracts in Reform? What happens is you deserialise a document and _then_ run a validation on that graph (for parsing). This also works the other way round, for rendering.

I am currently working on making it easier to infer contracts from representers, so you don't need to manage two classes. BTW, this already works partly in Trailblazer, I really want to work on this soon. Let me know what you think.

**Comment by grepory** [comment]
Wow Awesome! Thanks for the recommendations. I have been trying to wrap my head around this all morning. I'll check out Reform and Trailblazer. Also, upon re-reading the documentation for about the fifth time today, I realize that I have been Doing Representable All Wrong. :sweat_smile:

**Comment by apotonick** [comment]
What do you mean, all wrong? Hahahaha

My idea is to have a contract defined, which defines both document structure and validations. The contract then 

1. deserialises the incoming document using a representer that is inferred from the contract automatically.
2. validate the deserialised object graph using the contract.

I am convinced that this is the way to go for this complex workflow and I am craving to hack on that ASAP!!!!!

**Comment by grepory** [comment]
Basically, I was using Representable in a manner similar to ActiveRecord. Define fields, set them on an instance, and call to_json. E.g.

```
class Thing
  include Representable::JSON
  property :name
end

thing = Thing.new
thing.name = 'A name!'
thing.to_json
```

When in reality, Representable is just a layer between my Model and some serialization.

Basically, I did a terrible job of reading the documentation the first several times around.

Why not have a Model that has both a Representer and a Contract?

**Comment by apotonick** [comment]
Hey @grepory, the "model that has both representer and contract" is exactly what an `Operation` does in Trailblazer. Here, every concern (e.g. deserialisation, validation, etc.) is handled with different objects.

However, Reform is already capable of deserialising JSON instead of a hash, by applying the above outlined pattern internally. 

As far as I can see, you're not interested in deserialisation, it looks like you only need rendering. You basically would do the following in your app (without a Trailblazer operation).

```ruby
class Thing::Contract
  property :title

  validates :title, presence: true
end

contract = Thing::Contract.new(thing)
contract.validate
contract.to_json
```
Is that basically what you're after?

**Comment by grepory** [comment]
Yes! That is what I'm looking for.

I'll definitely take a look at Trailblazer. Thanks :)
