### ISSUE TITLE
Representable#cleanup_options implicit removal of user_options :include, :exclude need better doc warning

### ISSUE THREAD

**Issue by nonnenmacher** [apotonick/representable#137]
I spend several hours on an API problem, where I used a request parameter 'exclude' ('include' follow same rational) and this parameters was intended to be used into a property declaration like :

     property :owner, extend: UserRepresenter, class: :User,
            if: lambda { |options|
                  options[:exclude].nil? || ![options[: exclude]].flatten.include?(:owner) }

beside the fact, that it show bad taste, on my part in not pluralizing the denomination of an Array of what to 'exclude'
I fought hard to inject my option :exclude into the Representable @user_options.

The culprit, is inside this method in Representable
   
    def cleanup_options(options) # TODO: remove me. this clearly belongs in Representable.
      options.reject { |k,v| [:include, :exclude].include?(k) }
    end

I think the [TODO] merit some attention here ;-)
at least on the documentation standpoint, where a warning could be usefull.

I think, that the choice of 'include','exclude' are too good for user perspective, to be reserved for I guess protecting the :include, :exclude lambda/Proc that are injected into the DSL.

Proof, is that to correct my problem, I simply had to change my options[:exclude] to something like

     property :owner, extend: UserRepresenter, class: :User,
           if: lambda { |options|
                  options[:expose].nil? && options[:expose]].flatten.include?(:owner) }

But if I wanted to switch from Roar/Representable to Grape:Entity that use :expose in its own DSL, I could endure the same kind of trouble.

**Comment by apotonick** [comment]
Ouch, ok, I see that this is a problem for you. :laughing: 

However, the `:include` and `:exclude` options are documented as public API with a specific semantic. If you try to hijack that, things might fails (and did).

Do you think a note in the README will do?

**Comment by nonnenmacher** [comment]
I read the doc 'a lot', but as I missed that until I get to it inside the debugger, so I guess a more prominent warning will do on the |options| area when describing lambda, as other 'protected' term are not treated the same.

**Comment by apotonick** [comment]
Hmm, not sure if I understand? How is Representable supposed to know that the `:include` option passed into is yours and not following the regular usage?

**Comment by nonnenmacher** [comment]
I don't think Representable should know (or change anything).

But for example, on the doc, where you describe that a <Representable>.to_json(:include => 'my value')
this value will be discarded by the mentioned piece of code.

Did that make sense ?

**Comment by apotonick** [comment]
Absolutely, and I thought this is what I asked in my previous answer. :grimacing: Do you want to add that and PR? Thanks! :heart:

**Comment by nonnenmacher** [comment]
OK I'll try and you would certainly have to rewrite part of my 'frogy'
sentence ;-)
