### ISSUE TITLE
Possible problem upgrading 2.2.0 -> 2.2.1

### ISSUE THREAD

**Issue by jrmhaig** [apotonick/representable#139]
We are still investigating this problem but we started getting errors recently and the only change has been representable gem upgrading from 2.2.0 to 2.2.1.

```
undefined method `<<' for nil:NilClass (NoMethodError)
/home/devicehive/.rvm/gems/ruby-1.9.3-p448@hive-daemons/gems/virtus-1.0.5/lib/virtus/extensions.rb:65:in `attribute'
/home/devicehive/.rvm/gems/ruby-1.9.3-p448@hive-daemons/gems/virtus-1.0.5/lib/virtus/builder/hook_context.rb:44:in `block in initialize_attribute_method'
/home/devicehive/.rvm/gems/ruby-1.9.3-p448@hive-daemons/gems/hive-messages-1.0.0/lib/hive/messages/job.rb:8:in `<class:Job>'
(etc)
```

Representable isn't explicitly mentioned in the stack trace but 'hive-messages', one of our own gems, uses roar, which in turn uses representable, and the problem goes away when we fix the version of representable to 2.2.0.

We are still not clear where the problem lies but I thought it would be useful to raise here in case anyone else is seeing anything similar.

**Comment by apotonick** [comment]
Can you please paste a representer that uses coercion?

**Comment by apotonick** [comment]
@jrmhaig I looked into that. I'm guessing you use virus coercion manually in `Job`? I have no idea why that is a problem with Representable 2.2.1, though.

Can you make sure you're not using **coercion in a representer** (the `:type` option) and if you do, paste a sample representer here?

**Comment by jrmhaig** [comment]
We are in the process of open sourcing things so, although it is fairly useless by itself, I am able to make our hive-messages repository public so you can see how what the Job class looks like:

* https://github.com/bbc/hive-messages

**Comment by jrmhaig** [comment]
I have reduced this to what I believe is a minimal test that works with 2.2.0 and fails with 2.2.1.

```ruby
require 'rubygems'
#gem 'representable', '=2.2.0'
gem 'representable', '=2.2.1'
gem 'virtus'
gem 'roar'

require 'virtus'
require 'roar/json'

module Representers
  module JobRepresenter
    include Roar::JSON

    property :command
  end
end

require 'roar/client'

module Messages
  class Base
    include Virtus.model
    include Roar::JSON
    include Roar::Client
  end
end

module Messages
  class Job < Messages::Base
    include Representers::JobRepresenter

    attribute :command, String
  end
end
```

**Comment by jrmhaig** [comment]
I have further reduced it to:

```ruby
require 'rubygems'
#gem 'representable', '=2.2.0'
gem 'representable', '=2.2.1'
gem 'virtus'

require 'virtus'
require 'representable/json'

class Base
  include Virtus.model
  include Representable
end

class Job < Base
  property :command
  attribute :command, String
end
```

Interestingly, this works:

```ruby
require 'rubygems'
#gem 'representable', '=2.2.0'
gem 'representable', '=2.2.1'
gem 'virtus'

require 'virtus'
require 'representable/json'

class Job
  include Virtus.model
  include Representable
  property :command
  attribute :command, String
end
```

so it looks like it is to do with the class inheritance.

**Comment by apotonick** [comment]
I found the bug, I am a stupid idiot, please laugh at me: https://github.com/apotonick/representable/compare/v2.2.0...v2.2.1#diff-de25bf89e18d9382cf8e24d22abce389R92

When "cleaning up" the `::inherited` method I somehow deleted the `super` call. Thanks to your excellent bug report, @jrmhaig it took me only minutes to spot the issue. Thanks.

Releasing 2.2.2 now.
