### ISSUE TITLE
User options and deeply nested representers

### ISSUE THREAD

**Issue by AndrewSwerlick** [apotonick/representable#145]
I have a fairly deeply nested set of representers that looks something like this pseudo code

    Survey do 
      collection SurveyComponents do 
        property Deliverable do 
          collection Questions
        end
      end
   end

(Note in reality each representer is broken out into a seperate file, but I'm simplifying it here to describe the issue).

At the Deliverable level, I need to potentially randomize the order of the questions for each user, but keep the order the consistent every time a given user views them. I do that by having the deliverable representer receive a random seed based on the user id. However, when I'm trying to run `Survey.to_json(random_seed: user.id)` that random seed arg is not being passed along to the nested deliverables. The documentation seems to suggest that user options will be based along to nested representers, but is that limited to immediate children, or am I doing something wrong?

**Comment by apotonick** [comment]
Hm, that doesn't sound right, let me take a look at this. Options should be passed on every level.

**Comment by apotonick** [comment]
I wrote some more tests, and it looks as if you're doing something wrong. Any code for use?

**Comment by AndrewSwerlick** [comment]
Sorry just got back from vacation. Give me a day to dig out and I'll have
something.

~Andrew S.
