### ISSUE TITLE
Sync strategy on empty collection

### ISSUE THREAD

**Issue by rusikf** [apotonick/representable#146]
Hello @apotonick , Let's we have this example
```ruby
require 'pry'
require 'ostruct'
require 'representable/json'
require 'representable/xml'
require 'nokogiri'

class Car < OpenStruct
end

class Seria < OpenStruct
end

module SeriaRepresenter
  include Representable::JSON
  property :name
end

module CarRepresenter
  include Representable::JSON 
  property :name
  collection :series, extend: SeriaRepresenter, class: Seria, parse_strategy: :sync
end

puts Car.new(name: 'Volga', series: []).extend(CarRepresenter).from_hash("name" => "Ford", "series" => [{"name" => "s2"}])
# lib/representable/deserializer.rb:76:in `instance_for': :instance did not return object. (Representable::DeserializeError)

```
I think, in this case( Empty collection ) it should replace empty series collection with collection, containing s2. 
What you think about it ?

**Comment by apotonick** [comment]
Nope, `:sync` means it will synchronise element per element. Since you don't have any elements, this will fail.

I will replace `:parse_strategy` soon with populators, the way we use it in Reform, it's way less confusing.

**Comment by apotonick** [comment]
(Thanks for the very clear and concise example BTW, really helps!) :beers:
