### ISSUE TITLE
Find_or_instantiate parse_strategy

### ISSUE THREAD

**Issue by rusikf** [apotonick/representable#147]
Hello @apotonick , Let's we have this example
```ruby
require 'pry'
require 'ostruct'
require 'representable/json'
require 'representable/xml'
require 'nokogiri'

class Car < OpenStruct
end

class Seria < OpenStruct
end

module SeriaRepresenter
  include Representable::JSON
  property :name
end

module CarRepresenter
  include Representable::JSON 
  property :name
  collection :series, extend: SeriaRepresenter, class: Seria, parse_strategy: :find_or_instantiate
end

s1 = Seria.new(name: 's1')
puts Car.new(name: 'Volga', series: [s1]).extend(CarRepresenter).from_hash("name" => "Ford", "series" => [{"name" => "s2"}])
# parse_strategies.rb:53:in `block in apply!': undefined method `find_by' for Seria:Class (NoMethodError)
```
May be in this case, it should also replace ```series``` collection? And if series is empty on initialization, it should also replace ```series``` collection. What you think about it ?

**Comment by apotonick** [comment]
Again, this is not the defined semantic of `:find_or_instantiate`. This option will "hardcore" call `Whatever.find(fragment["id"])` regardless of whether or not that class responds to that.

It's an option, you as the user have to know whether or not this works for you. Why replace the series collection? They are two different objects, unfortunately they don't have `id` fields so `:find_or_instantiate` is the wrong strategy here. 

What are you trying to do? Maybe we can use a manual strategy/populator?

**Comment by rusikf** [comment]
@apotonick , I read docs and tried some examples for more "clear understanding". Year, I think in this case, if it will be important, I can use manually created parse strategy. Thanks for explanation!
