### ISSUE TITLE
How to access parent object within inline nested blocks?

### ISSUE THREAD

**Issue by gottfrois** [apotonick/representable#152]
I have the following models:

```ruby
class Song
  belongs_to :author
end

class Author
end
```

and the following representer:

```ruby
module Song
  include Roar::JSON

  nested :relationships do
    property :author do
      nested :links do
        property :related, getter: ->(_) { #calling id here will refer to author.id }
      end
    end
  end
end
```

I would like to build the `related` link by including the song `id`. How can I access the song `id` within the `author` getter?

In the end I want to build the following url: `/songs/:song_id/author`

**Comment by apotonick** [comment]
You can either pass the song into the render call as documented here: https://github.com/apotonick/representable/#passing-options

Or you have to make your author object know about the song relationship, maybe by introducing an intermediate decorator. Remember, Representable is a document-mapper and not an ORM, it doesn't know about your domain and object graphs.

I will talk about that in my new book _OOP For Real_, but basically, the domain you want has the following API:

```ruby
song.id #=> 1
song.author #=> <Author>
song.author.song #=> <Song>
```

You understand where this is heading? It's your job to provide the correct object graph to Representable, not vice-versa. :wink: Anyway, I would suggest you use my first point with the options?

**Comment by gottfrois** [comment]
Hmm but an Author could have many songs. There is no one-to-one mapping here. Also I find it super strange to have to pass the song instance as an option since this is the primary object i'm decorating.

```
song = Song.first
song.to_json(song: song)
```

Really look weird and from an outsider, unnecessary.

**Comment by apotonick** [comment]
Well, again, Representable is a document-mapper. The way you model your domain (which in this case is a song object with _one_ author) is "your problem", Representable has no way of knowing what exactly you want to do with the represented object. Also, this might look like something trivial to you, but imagine this was a 5-level deep nested structure, now what is the "top-level" object, etc.?

I _could_ think of an extension to `Representable::Decorator` (that would only work with decorator classes).

```ruby
class SongDecorator < Representable::Decorator
  include Representable::JSON
  include Representable::Parent

  nested :relationships do
    property :author do
      nested :links do
        property :related, getter: ->(*) { parent.represented.id }
      end
    end
  end
end

SongDecorator.new(song).to_json
```

As you can see, we could pass the parent object to the child decorator instances, that way, you could access `parent` (which is a decorator that responds to `#represented` which in turn is the decorated object.

**Comment by gottfrois** [comment]
Thanks for the explanation. I wonder how we are going to deal with such feature on Roar. This is a format used in JSONAPI format.

**Comment by apotonick** [comment]
Well, for a specific media type, this is a different thing, as you would simply mix in `Roar::JSONAPI` and this takes care of this internally, e.g. by passing around models to child decorators using the technique described earlier.

I thought you need a generic solution, but if you "only" want to render JSON-API, I wonder, have you seen `Roar::JSONAPI`? It's here: https://github.com/apotonick/roar/tree/jsonapi

**Comment by gottfrois** [comment]
Yes, I contributed to it ;) But it's currently not working for latest JSONAPI format (v1.0). Basically I'm trying to render JSONAPI valid json using roar and representable directly. If I can have something working, I could consider helping to finalize the JSONAPI branch on roar.

But now I hit this wall where I need to have this "parent" idea when declaring related links.

**Comment by apotonick** [comment]
Ah, ok, haha! Can't you get further with the `to_hash(parent: represented)` trick? You could override `to_hash` and do that per default? I will soon get back to Roar, as I'm finishing chapter 10 of the Trailblazer book, and chapter 11 is Roar!!!!

**Comment by apotonick** [comment]
BTW, "soon" as in next week or so, so we can work on `JSONAPI` together. You should join the https://gitter.im/trailblazer/chat to discuss details, it's so much better for communication! :beers:

**Comment by gottfrois** [comment]
Alright, I won't loose too much time on this then. I can wait for links representation. My goal was to have a JSONAPI format structure like, in place.

Thanks for looking at this. Let's continue talking over gitter :)
