### ISSUE TITLE
How to set wrapper for xml and disable it for json within one module?

### ISSUE THREAD

**Issue by PositiveAlex** [apotonick/representable#153]
Hey, man)

I have to work with xml and json output simultaneously.
For that, I created representers with both XML and JSON support.

f.i.

```ruby
module StringValueRepresenter
  include Representable::JSON
  include Representable::XML

  self.representation_wrap = lambda do | obj |
    if obj.empty?
      false
    else
      :item
    end
  end

  property :value
end
```

I wrote this ugly code inside of the module to turn off wrap mode while we are dealing with json and to set a wrapper name while it's an xml document.

If I write something like this: `self.representation_wrap = false`, in json mode it is ok, but `to_xml` mode wraps this object with `<false>` , which is, *imo*, a little bit awkward.

Can you tell me the better way of how to set the wrapper only for an xml representation?

Thanks ^_^

**Comment by apotonick** [comment]
Hey Alex, this "feature" is not documented and public, you can't include two engines into one module (you can, and it kinda works, but there's problems). You have to maintain two separate representers for each format, and then you can have different wraps, too.

Sharing of generic declarations works via normal Ruby modules. Does that help?

**Comment by PositiveAlex** [comment]
Yes, thanks for your answer. Please, close the issue.

ср, 16 сент. 2015, 3:54, Nick Sutterer <notifications@github.com>:

**Comment by apotonick** [comment]
Out of curiosity: Are you gonna leave the representer with the `if` or will you introduce two modules/classes? And: What's your preferred approach?

**Comment by PositiveAlex** [comment]
@apotonick I have decided to leave this hack inside:

1. I created a json/xml structure generator which contains ~10 different classes
2. I didn't face any other problems while generating output stuff so there's no reason to do it `the right way` now
3. If I will face with problems, I'm sure I define 10 modules more :)

Off the topic:

> I surfed on the internet about simultaneous xml/json rest api testing but there is no anything about this.
> 
> We're testing huge rest api which must work in xml and json modes without errors and glitches in its output documents. 
> So i'm creating tests which can work in both modes: one test to both accept types.
> 
> The info for the Rest API best practices says that API must support both formats, 
> but if to draw conclusions from what information I find online, everyone test either 
> xml or json and I didn't found such automated solutions just not to kill yourself 
> while duplicating amount of your work under automated tests and maintainig it then.

**Comment by apotonick** [comment]
Interesting, wait, so you use Representable to generate test output for an actual API? What is the API itself written in? And: why do you need both formats? Is the API really popular amongst both users?

You did the right thing by using one - as long as the output works for you. I _might_ allow that some day in the future, but then you're on the save side because it already worked for you anyway. :wink:

**Comment by PositiveAlex** [comment]
Yes, I generate requests for api using liquid templates and appending
polymorphic lists generated by representable to a request.

The problem is that our api is  commercial product, we need to make it work
in both formats out of the box as described in tecnical specs so its not
connected with popularity, we just need to provide this in our product :)

чт, 17 сент. 2015, 3:44, Nick Sutterer <notifications@github.com>:

**Comment by PositiveAlex** [comment]
Not test output. But requests to test api from outside. Integration testing.

чт, 17 сент. 2015, 3:44, Nick Sutterer <notifications@github.com>:

**Comment by PositiveAlex** [comment]
The api itself written on java and as practice shows , junit tests are not
able to find al bugs.

чт, 17 сент. 2015, 3:44, Nick Sutterer <notifications@github.com>:

**Comment by apotonick** [comment]
Ok, sorry, I meant to say "integration test _input_". Why the liquid deviation instead of using Representable for that?

**Comment by PositiveAlex** [comment]
By historical reasons... 

It's because we used cucumber as basis for test framework for legacy api... 
All queries were compiling through cucumber tables with xpath and value (nokogiri) and xml template + checkers to responses.

1. With cucumber table, I am able to pass variables from cucumber feature to liquid template directly, just writing variables and values and nothing more. 
2. We should mix scenarios with legacy api because work in progress and legacy scenarios work with cucumber only. To make legacy scenarios work in other environment, we would refactor whole thing anyway. 
3. Tests does not lose their readability because of cucumber scenarios.

To use Representable, we would refuse cucumber at all and write rake tests on ruby for instance. Or on any language. 

It's double time-consuming because we would refactor also legacy tests to be able to test the whole business workflow.

The main idea why legacy framework was developed with cucumber was in writing tests which could be readable by a non programmer.

I'm talking with colleagues and they are saying that Ruby is quite dead language... and it's sad, because I very like it. Some other guys suggest me to rewrite the whole framework on golang or python in future.

**Comment by apotonick** [comment]
Your colleagues probably confused _"Rails"_ and _"Ruby"_?

**Comment by PositiveAlex** [comment]
Well, they argument it by the idea that common ruby driver is rails and rails is not so popular to make ruby more popular and growing...

**Comment by PositiveAlex** [comment]
And also benchmark stats...

**Comment by apotonick** [comment]
Let them talk, Ruby is not going to die.
