### ISSUE TITLE
Represent a lone hash with properties

### ISSUE THREAD

**Issue by moxley** [apotonick/representable#154]
In https://github.com/apotonick/representable#lonely-hashes section of the readme, it shows that hashes can have representers. However, it seems to ignore any `property` definitions, and when `#to_hash` or `#to_json` is called on the represented hash, all the keys of the hash are exposed rather than the ones defined by the `property` definitions.

For example:

```ruby
require 'representable/json/hash'

module ProductRepresenter
  include Representable::JSON::Hash

  property :title
  property :price
end

{"title" => "Black Socks", "price" => "5.99", "upc" => "1111222233334444"}.extend(ProductRepresenter).to_json
#=> {"title":"Black Socks","price":"5.99","upc":"1111222233334444"}"
```

Above, it includes `upc` in the output, even though it was never specified in the properties. So that got me wondering, what is the purpose of `Representable::JSON::Hash`? Looks like all it does is convert any given hash to JSON. That can already be done with: `require 'json'; my_hash.to_json`

**Comment by apotonick** [comment]
Just after the introducing paragraph there's the `::values` class method documented which allows typing for the hash values. What you want (I'm guessing here) is a real representer without the `Representable::JSON::Hash` module mixed in!

**Comment by apotonick** [comment]
Ok, I reread and am trying to understand your goal. You have a hash you want to represent, and you don't want to take the detour via an `OpenStruct` and a normal representer, is that right?

**Comment by moxley** [comment]
That's right. The workaround is wrapping the represented hash in an
OpenStruct, but that can get tricky when the object has child objects that
in turn need to be represented, so then there are ways to recursively wrap
such a hash in OpenStructs with some supporting code. But with that comes
the baggage of support code and potential performance drawbacks.

If this isn't built into representable, I'm fine with that. I just wanted
to make sure I wasn't missing something that was already built in.

**Comment by apotonick** [comment]
This is another reason why I introduced _twins_ in Disposable! The [twin will map](https://github.com/apotonick/disposable#struct) your data structure to a data object that Representable understands, so Representable focuses on rendering/parsing to and from an object and doesn't know anything about the underlying data structure.

The twin, on the other hand, has no idea about JSON and nested hashes but provides readers and writers and then maps that back to the underlying datastructure. It's way easier to understand and - for me - to implement. This also works great with forms, etc. where the form can basically map to a hash structure.

**Comment by moxley** [comment]
`disposable` and the twins feature looks cool. I may try that out sometime. Thanks for the help!
