### ISSUE TITLE
Scrub input fragment before parsing

### ISSUE THREAD

**Issue by ketan** [apotonick/representable#156]
What's the best way to scrub the input json/hash data before parsing things?

Rails [`deep_munge`](https://github.com/rails/rails/pull/13157) seems to transform empty arrays into nils. So for e.g. `{"name": "foo", "songs": []}` becomes ```{"name": "foo", "songs": nil}`. Representable is unable to handle nils where collections are expected.

I've tried `skip_parse` but that seems to applies to individual elements in the array. `parse_filter` also does not seem to work.

What's the best way to scrub this to convert `nil` into blank arrays? 

```ruby
class SkipParseOnCollectionTest < MiniTest::Spec

  class SongRepresenter < Representable::Decorator
    include Representable::Hash
    include Representable::Hash::AllowSymbols
    property :name
  end

  class AlbumRepresenter < Representable::Decorator
    include Representable::Hash
    include Representable::Hash::AllowSymbols

    # replace parse_filter with other options if needed
    collection :songs, 
      class:        Song, 
      decorator:    SongRepresenter, 
      parse_filter: lambda { |fragment, doc, opts| fragment || [] }
  end

  it 'skips parsing collections when parse_filter is configured' do
    album = Album.new
    AlbumRepresenter.new(album).from_hash(name: 'Fat Wreck', songs: nil)

    assert_equal album.songs.length, 0
  end
end
```

**Comment by p-lambert** [comment]
I'm having the very same problem here. I've also tried to use `parse_filter`, but it's indeed supposed to work on each member of the collection. I think one way to address this that could be useful in other scenarios would be yield a `doc` hash argument to the `if` lambda. That way we could at least disable a collection parsing like this:
```ruby
collection(
  :songs, 
  class: Song, 
  decorator: SongRepresenter, 
  if: -> (_, doc) { !doc[:songs] }
)
```

**Comment by apotonick** [comment]
With representable 2.4.0 this works by defining you own `parse_pipeline`! I will blog about it soon.

**Comment by apotonick** [comment]
Here is an example how that works in 2.4. https://github.com/apotonick/representable/blob/2b3d8c2bb8a0aa3e90f45bb8547de273e4dda864/test/parse_pipeline_test.rb#L12

The code is called once and then cached and replaces `OverwriteOnNil` with your own piece of logic in the `parse_pipeline`.

Please let me know if you're happy with that! :beers:
