### ISSUE TITLE
Representable::Set shadows ruby core class Set

### ISSUE THREAD

**Issue by felixbuenemann** [apotonick/representable#157]
The file `lib/representable/deserializer.rb` defines a proc called `Representable::Set`, which causes problems if a representer uses the ruby core class `Set` without fully qualifying it to `::Set`.

Maybe a less problematic name could be used for the proc?

**Comment by felixbuenemann** [comment]
Thanks, Nick!

**Comment by apotonick** [comment]
Thanks to you! `Set` was a bit too much of a common name, especially directly in the `Representable` namespace.

**Comment by felixbuenemann** [comment]
Yes, combined with ruby's cascading constant lookup it can be irritating.
