### ISSUE TITLE
HashMethods: uninitialized constant Representable::Pipeline::Debug

### ISSUE THREAD

**Issue by felixbuenemann** [apotonick/representable#158]
I get a NameError exception if I try to call to_json on a Roar::JSON representer using representable 2.4.0.rc2.

The problem seems to be that `lib/representable/pipeline.rb` does not define the constant `Pipeline::Debug` referenced in `lib/representable/hash_methods.rb:7`.

**Comment by felixbuenemann** [comment]
I checked and `lib/representable/debug.rb` defines that constant, but it is not required automatically by the gem.

**Comment by apotonick** [comment]
Oh thanks, that shouldn't be referenced at all!
