### ISSUE TITLE
Callable object args not matching what's in README

### ISSUE THREAD

**Issue by davidcpell** [apotonick/representable#161]
I had been using lambdas with `parse_filter` etc for a long time and then discovered the 'callable object' pattern in the README:

```
class Sanitizer
  include Uber::Callable

  def call(represented, fragment, doc, *args)
    fragment.sanitize
  end
end
```

However, when I implement this the args that are actually passed to my callable object don't seem to match with what is described in the README. 

My JSON doc looks like this (key part is the nested 'time' object):
```
"{\"player\":{\"playerId\":168396,\"firstName\":\"Wayne\",\"lastName\":\"Gretzky\",\"uniform\":\"Foo\"},\"teamId\":4966,\"time\":{\"minutes\":16,\"seconds\":15},\"penaltyType\":{\"penaltyTypeId\":13,\"name\":\"Holding\"},\"penaltyMinutes\":2}"
```

My representer: 

```
module PenaltyRepresenter
   include Representable::JSON2
   include RepresenterHelper

   property :mins, as: :penaltyMinutes
   property :at,      as: :time, parse_filter: SecondsFromHash.new
 end
```

The `SecondsFromHash` class is in `RepresenterHelper`:

```
module RepresenterHelper
   class SecondsFromHash
     include Uber::Callable

     def call(represented, fragment, doc, *args)
       binding.pry
     end
   end
 end
```

When I run my test and get a console at the `binding.pry` point, the args are such:

```

    14: def call(represented, fragment, doc, *args)
 => 15:   binding.pry
    16: end

[1] pry(#<RepresenterHelper::SecondsFromHash>)> represented
=> {"minutes"=>16, "seconds"=>15}
[2] pry(#<RepresenterHelper::SecondsFromHash>)> fragment
=> {"player"=>
  {"playerId"=>168396, "firstName"=>"Wayne", "lastName"=>"Gretzky", "uniform"=>"Foo"},
 "teamId"=>4966,
 "time"=>{"minutes"=>16, "seconds"=>15},
 "penaltyType"=>{"penaltyTypeId"=>13, "name"=>"Holding"},
 "penaltyMinutes"=>2}
[3] pry(#<RepresenterHelper::SecondsFromHash>)> doc
=> {}
```

So `represented` is actually the fragment targeted by my `property` keyword, `fragment` is `doc`, and `doc` is empty. 

If I use `setter` instead of `parse_filter` in my representer: 
`property :at,   as: :time, setter: SecondsFromHash.new`

...I get the following: 

```

    14: def call(represented, fragment, doc)
 => 15:   binding.pry
    16: end

[1] pry(#<RepresenterHelper::SecondsFromHash>)> represented
=> #<Nhl::Penalty id: nil, game_player_id: nil, team_penalty: nil, name: nil, at: nil, mins: 2, created_at: nil, updated_at: nil>
[2] pry(#<RepresenterHelper::SecondsFromHash>)> fragment
=> {"minutes"=>16, "seconds"=>15}
[3] pry(#<RepresenterHelper::SecondsFromHash>)> doc
=> {}
```

Now `represented` and `fragment` are correct, but `doc` is still empty. 

Am I using this incorrectly or maybe there's something else I am missing? If it's working as intended I'd be happy to contribute to the README...if something is actually broken I can look into it but I've never made a major contribution to open source so it might take a bit. :)

**Comment by apotonick** [comment]
Please use Representable 2.4 (on master branch) which unifies this. http://nicksda.apotomo.de/2015/11/representable-2-4-how-functional-programming-speeds-up-rendering-and-parsing/

The README is not up-to-date with the new API, I will move the README once I got time, in about 7 years. :beers:

**Comment by davidcpell** [comment]
thanks!
