### ISSUE TITLE
2.4.0.rc4 'ArgumentError: unknown keywords' when using keywords args w/unified lambda args

### ISSUE THREAD

**Issue by davidcpell** [apotonick/representable#166]
Loving 2.4 so far! Today I ran into an issue with the keyword args option for lambdas:

Using this per the blog example:

```ruby
  property :team_id, 
    as: :teamId, 
    setter: ->(fragment:, doc:) { puts "#{fragment}" }
```

...raises the following exception:

```bash
ArgumentError:         ArgumentError: unknown keywords: options, represented, decorator, binding, input, as, user_options
```

If I add more keyword args (e.g. `decorator:`), that arg disappears from the error list. Likewise if I take keyword args away, they appear in the error list. It seems as if I'm being expected to either pass a singular variable 'options' or every single keyword possible variable. 

Using `options`: 

```ruby
  property :team_id, 
    as: :teamId, 
    setter: ->(options) { puts options[:doc] }
```

...works without raising any exceptions. 

So far I've had to resort to the old positional args to get the desired behavior:

```ruby
  property :team, 
    as: :teamId, 
    setter: ->(val, *) do 
      self.team = team_model.stats_find(val)
    end
```

**Comment by apotonick** [comment]
You simply have to use the hash splat for keyword arguments.

`->(fragment:, **)`

I will update the blog post, thanks!
