### ISSUE TITLE
2.4.0.rc4 `as` option seems to be ignored when also using `parse_pipeline`

### ISSUE THREAD

**Issue by davidcpell** [apotonick/representable#167]
I have a doc like this that is being passed in my test to `GameRepresenter`:

```ruby
    doc = {
      eventId: 1539149,
      eventRound: {
        gamesInSeries: 7,
        eventRoundId: 1,
        name: "Round 1"
      },
      seriesGameNumber: 1
    }.to_json
```

I am trying to build a `Postseason` object that is a child (one-to-one) of `Game` like this using the new `parse_pipeline` feature:

```ruby
  SetPostseason = ->(input, opts) {
    binding.pry
    # input.merge(game_in_series: opts[:doc]['seriesgameNumber']) <--- intended use
    # but here input == opts[:doc] returns true
  }

  property :postseason, 
      as: :eventRound,
      instance: Nhl::Postseason.new, # don't think this or :extend below are doing anything
      extend: PostseasonRepresenter, 
      parse_pipeline: ->(*) { SetPostseason }
```

The problem I'm attempting to solve is that I need to bring one property from the top-level doc into the inner `eventRound` object, which maps to a `Postseason`. I was expecting `input` inside my lambda to be equal to `eventRound` since I'm using `as: :eventRound` in the main property declaration. However, inside the lambda the `input` arg is equal to the entire doc. 

Right now I'm falling back to hacking it with this:

```ruby
  SetPostseason = ->(input, opts) {
    doc = input['eventRound'].merge('num_in_series' => input['seriesGameNumber'])
    ps = opts[:represented].postseason || opts[:represented].build_postseason
    ps.extend(PostseasonRepresenter).from_hash(doc)
  }

  property :postseason, # notice it works without as: :eventRound
    parse_pipeline: ->(*) { SetPostseason }
```
This causes my test that a `Postseason` object is built to pass. However, I'm also finding that `SetPostseason` is being called even in tests where my json document _doesn't_ have the nested `eventRound` object, causing those tests to fail at the line with `#merge` inside `SetPostseason` because the expected keys don't exist in the `input` or the `opts[:doc]` objects. `property :postseason` is running every time, regardless of whether `:as` is used.

Are these bugs or does using `parse_pipeline` disrupt the normal flow of things so that `as` isn't being recognized first?

**EDIT**

I read back through the blog post and realized I had misunderstood how the pipeline works. At this point I think i just need clarification on usage but am not sure this is the best place for that. Should I close this and post on StackOverflow? Is there a better way for me to ask questions for clarification on usage?

**Comment by apotonick** [comment]
Yeah, when overriding the pipeline options like `:as` don't take effect anymore as their function is missing. You should inject a function into the existing pipeline.

Best place to discuss is https://gitter.im/trailblazer/chat - I don't think that SO will help right now since the pipeline is brand new.
