### ISSUE TITLE
Possibly incorrect skip_render usage in README

### ISSUE THREAD

**Issue by dvogel** [apotonick/representable#175]
The README shows the `skip_render` lambda taking two arguments but that yields `ArgumentError (wrong number of arguments (1 for 2)` in practice. Is the README out of date or is this a bug in 2.4?

**Comment by apotonick** [comment]
README's outdated, docs for 2.4 here: http://trailblazer.to/gems/representable/3.0/function-api.html#skip-render

Sorry for the inconvenience - all docs will be moved to the Trailblazer site!
